package io.github.aedev.flow.data.sponsordetection

import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.test.runTest
import org.junit.Test
import java.nio.file.Files

class SponsorInferenceCacheTest {
    @Test
    fun `cache hit returns predictions without transcript text`() =
        runTest {
            val directory = Files.createTempDirectory("sponsor-inference-cache").toFile()
            val cache = SponsorInferenceCache(directory)
            val transcript = sampleTranscript("hello")
            val result =
                SponsorInferenceResult(
                    videoId = "video",
                    transcript = transcript,
                    transcriptSha256 = sponsorTranscriptSha256(transcript),
                    spans = listOf(SponsorPredictedSpan("p", 1_000, 2_000, 0.5)),
                    inferenceMs = 12,
                )

            cache.put(result)
            val cached = cache.get("video", transcript)

            assertThat(cached?.fromCache).isTrue()
            assertThat(cached?.spans).isEqualTo(result.spans)
            assertThat(directory.listFiles()?.joinToString { it.readText() }).doesNotContain("hello")
        }

    @Test
    fun `expired entries are ignored`() =
        runTest {
            var now = 1_000L
            val cache =
                SponsorInferenceCache(
                    directory = Files.createTempDirectory("sponsor-inference-expired").toFile(),
                    nowMs = { now },
                    maxAgeMs = 10,
                )
            val transcript = sampleTranscript("copy")
            cache.put(
                SponsorInferenceResult(
                    videoId = "video",
                    transcript = transcript,
                    transcriptSha256 = sponsorTranscriptSha256(transcript),
                    spans = listOf(SponsorPredictedSpan("p", 1_000, 2_000, 0.5)),
                    inferenceMs = 1,
                ),
            )
            now = 1_020L

            assertThat(cache.get("video", transcript)).isNull()
        }

    @Test
    fun `oldest entries are evicted past the max`() =
        runTest {
            var now = 1_000L
            val directory = Files.createTempDirectory("sponsor-inference-evict").toFile()
            val cache =
                SponsorInferenceCache(
                    directory = directory,
                    nowMs = { now },
                    maxEntries = 1,
                )
            val first = sampleTranscript("first")
            val second = sampleTranscript("second")
            cache.put(result("one", first))
            now = 2_000L
            cache.put(result("two", second))

            assertThat(cache.get("one", first)).isNull()
            assertThat(cache.get("two", second)?.videoId).isEqualTo("two")
        }

    @Test
    fun `cache key changes with the decode logic version`() {
        val first = sponsorPredictionCacheKey("video", "hash", logicVersion = 1)
        val second = sponsorPredictionCacheKey("video", "hash", logicVersion = 2)

        assertThat(first).isNotEqualTo(second)
        assertThat(sponsorPredictionCacheKey("video", "hash", logicVersion = 2)).isEqualTo(second)
        assertThat(sponsorPredictionCacheKey("video", "other", logicVersion = 2)).isNotEqualTo(second)
    }

    private fun result(
        videoId: String,
        transcript: SponsorTranscriptPayload,
    ) = SponsorInferenceResult(
        videoId = videoId,
        transcript = transcript,
        transcriptSha256 = sponsorTranscriptSha256(transcript),
        spans = listOf(SponsorPredictedSpan("p", 1_000, 2_000, 0.5)),
        inferenceMs = 1,
    )

    private fun sampleTranscript(text: String) =
        SponsorTranscriptPayload(
            languageTag = "en",
            source = SponsorTranscriptSource.YOUTUBE,
            isAutoGenerated = false,
            cues = listOf(DetectionTranscriptCue(0, 1_000, text)),
        )
}
