package io.github.aedev.flow.data.sponsordetection

import android.content.Context
import io.github.aedev.flow.data.model.SponsorBlockSegment
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.security.MessageDigest

const val SPONSOR_MODEL_SHA256 = "53b3bc2869db22382d4db036f7dceaa14054571225ae7d7761e4534873f4aa89"
const val SPONSOR_TOKENIZER_SHA256 = "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30"

/** Operating point calibrated to the sponsor-only model's weights. */
const val SPONSOR_CONFIDENCE_THRESHOLD = 0.7

/**
 * Bump whenever the on-device decode/stitch logic changes. The prediction cache keys on this so a
 * result produced by older logic is never replayed against new decoding.
 */
const val SPONSOR_DECODE_LOGIC_VERSION = 3

private const val ON_DEVICE_UUID_PREFIX = "flow-ml-"

/** Model predictions are suggestions: the player offers a skip button for them and never skips on its own. */
fun SponsorBlockSegment.isOnDevicePrediction(): Boolean = uuid.startsWith(ON_DEVICE_UUID_PREFIX)

@Serializable
internal data class SponsorPredictedSpan(
    @SerialName("span_id") val spanId: String,
    @SerialName("start_ms") val startMs: Long,
    @SerialName("end_ms") val endMs: Long,
    val confidence: Double,
) {
    init {
        require(spanId.isNotBlank())
        require(startMs >= 0)
        require(endMs > startMs)
        require(confidence in 0.0..1.0)
    }

    fun asSponsorBlockSegment(videoId: String): SponsorBlockSegment =
        SponsorBlockSegment(
            category = "sponsor",
            segment = listOf(startMs / 1000f, endMs / 1000f),
            uuid = "$ON_DEVICE_UUID_PREFIX$videoId-$spanId",
            actionType = "skip",
        )
}

internal enum class SponsorTranscriptSource {
    YOUTUBE,
    OFFLINE_CAPTION,
}

internal data class SponsorInferenceResult(
    val videoId: String,
    val transcript: SponsorTranscriptPayload,
    val transcriptSha256: String,
    val spans: List<SponsorPredictedSpan>,
    val windowCount: Int = 0,
    val confidenceThreshold: Double = SPONSOR_CONFIDENCE_THRESHOLD,
    val inferenceMs: Long,
    val fromCache: Boolean = false,
) {
    val playbackSegments: List<SponsorBlockSegment>
        get() = spans.map { it.asSponsorBlockSegment(videoId) }
}

internal fun sponsorTranscriptSha256(transcript: SponsorTranscriptPayload): String {
    val canonical =
        buildString {
            append(transcript.languageTag)
            append('|')
            append(transcript.source.name)
            append('|')
            append(transcript.isAutoGenerated)
            transcript.cues.forEach { cue ->
                append('\n')
                append(cue.startMs)
                append('|')
                append(cue.endMs)
                append('|')
                append(cue.text)
            }
        }
    return sha256(canonical)
}

internal fun sha256(value: String): String =
    MessageDigest
        .getInstance("SHA-256")
        .digest(value.toByteArray(Charsets.UTF_8))
        .joinToString("") { "%02x".format(it) }

internal fun sha256File(file: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    file.inputStream().buffered().use { input ->
        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
        var read = input.read(buffer)
        while (read >= 0) {
            digest.update(buffer, 0, read)
            read = input.read(buffer)
        }
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}

internal interface SponsorPredictionCache {
    suspend fun get(
        videoId: String,
        transcript: SponsorTranscriptPayload,
    ): SponsorInferenceResult?

    suspend fun put(result: SponsorInferenceResult)
}

/** Binds the model, tokenizer and decode logic so changing any of them invalidates cached spans. */
internal fun sponsorPredictionCacheKey(
    videoId: String,
    transcriptHash: String,
    logicVersion: Int = SPONSOR_DECODE_LOGIC_VERSION,
): String = sha256("$videoId|$SPONSOR_MODEL_SHA256|$SPONSOR_TOKENIZER_SHA256|$logicVersion|$transcriptHash")

internal class SponsorInferenceCache(
    private val directory: File,
    private val json: Json = Json { ignoreUnknownKeys = true },
    private val nowMs: () -> Long = { System.currentTimeMillis() },
    private val maxAgeMs: Long = DEFAULT_MAX_AGE_MS,
    private val maxEntries: Int = DEFAULT_MAX_ENTRIES,
) : SponsorPredictionCache {
    constructor(context: Context) : this(File(context.cacheDir, "sponsor_detection"))

    override suspend fun get(
        videoId: String,
        transcript: SponsorTranscriptPayload,
    ): SponsorInferenceResult? =
        withContext(Dispatchers.IO) {
            val transcriptHash = sponsorTranscriptSha256(transcript)
            val key = cacheKey(videoId, transcriptHash)
            val file = File(directory, "$key.json")
            val entry = runCatching { json.decodeFromString<CachedInference>(file.readText()) }.getOrNull() ?: return@withContext null
            if (nowMs() - entry.createdAtEpochMs > maxAgeMs) {
                file.delete()
                return@withContext null
            }
            file.setLastModified(nowMs())
            SponsorInferenceResult(
                videoId = videoId,
                transcript = transcript,
                transcriptSha256 = transcriptHash,
                spans = entry.spans,
                windowCount = entry.windowCount,
                confidenceThreshold = entry.confidenceThreshold,
                inferenceMs = entry.inferenceMs,
                fromCache = true,
            )
        }

    override suspend fun put(result: SponsorInferenceResult) =
        withContext(Dispatchers.IO) {
            directory.mkdirs()
            val entry =
                CachedInference(
                    createdAtEpochMs = nowMs(),
                    inferenceMs = result.inferenceMs,
                    spans = result.spans,
                    windowCount = result.windowCount,
                    confidenceThreshold = result.confidenceThreshold,
                )
            val file = File(directory, "${cacheKey(result.videoId, result.transcriptSha256)}.json")
            file.writeText(json.encodeToString(entry))
            file.setLastModified(nowMs())
            directory
                .listFiles { file -> file.extension == "json" }
                .orEmpty()
                .sortedByDescending(File::lastModified)
                .drop(maxEntries)
                .forEach(File::delete)
        }

    private fun cacheKey(
        videoId: String,
        transcriptHash: String,
    ): String = sponsorPredictionCacheKey(videoId, transcriptHash)

    @Serializable
    private data class CachedInference(
        val createdAtEpochMs: Long,
        val inferenceMs: Long,
        val spans: List<SponsorPredictedSpan>,
        val windowCount: Int = 0,
        val confidenceThreshold: Double = 0.0,
    )

    private companion object {
        const val DEFAULT_MAX_ENTRIES = 500
        const val DEFAULT_MAX_AGE_MS = 30L * 24L * 60L * 60L * 1000L
    }
}
