package io.github.aedev.flow.data.sponsordetection

import android.content.Context
import android.util.Log
import io.github.aedev.flow.network.AppProxyManager
import io.github.aedev.flow.player.stream.CaptionTrackResolver
import io.github.aedev.flow.player.stream.ResolvedCaption
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.net.URI
import java.util.Locale

internal data class SponsorTranscriptPayload(
    val languageTag: String,
    val source: SponsorTranscriptSource,
    val isAutoGenerated: Boolean,
    val cues: List<DetectionTranscriptCue>,
)

internal class SponsorCaptionLoader(
    private val context: Context,
) {
    private val client: OkHttpClient by lazy { AppProxyManager.applyTo(OkHttpClient.Builder()).build() }

    suspend fun load(streams: List<ResolvedCaption>): SponsorTranscriptPayload? =
        withContext(Dispatchers.IO) {
            val stream = selectEnglishTrack(streams)
            if (stream == null) {
                Log.i(TAG, "Sponsor captions unavailable: no usable English track in ${streams.size} streams")
                return@withContext null
            }
            val content = fetchVtt(stream)
            if (content == null) {
                Log.i(TAG, "Sponsor captions unavailable: caption download failed")
                return@withContext null
            }
            val cues = parseWebVtt(content)
            if (cues.isEmpty()) {
                Log.i(TAG, "Sponsor captions unavailable: no cues parsed")
                return@withContext null
            }
            Log.i(TAG, "Sponsor captions loaded: ${cues.size} cues")
            SponsorTranscriptPayload(
                languageTag = stream.languageTag.ifBlank { "en" },
                source =
                    if (stream.url.startsWith("file:")) {
                        SponsorTranscriptSource.OFFLINE_CAPTION
                    } else {
                        SponsorTranscriptSource.YOUTUBE
                    },
                isAutoGenerated = stream.isAutoGenerated,
                cues = cues,
            )
        }

    private fun selectEnglishTrack(streams: List<ResolvedCaption>): ResolvedCaption? =
        streams
            .asSequence()
            .filterNot { it.isTranslated }
            .filter {
                it.languageTag
                    .substringBefore('-')
                    .substringBefore('_')
                    .equals("en", ignoreCase = true)
            }.sortedBy { it.isAutoGenerated }
            .firstOrNull()

    private fun fetchVtt(stream: ResolvedCaption): String? {
        val content = stream.url
        if (content.startsWith("file:")) {
            return runCatching { File(URI(content)).readText() }.getOrNull()
        }
        val url =
            content
                .toHttpUrlOrNull()
                ?.newBuilder()
                ?.removeAllQueryParameters("fmt")
                ?.removeAllQueryParameters(CaptionTrackResolver.TRANSLATED_PARAM)
                ?.addQueryParameter("fmt", "vtt")
                ?.build()
                ?: return null
        return runCatching {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                response.body.string().takeIf { response.isSuccessful && it.startsWith("WEBVTT") }
            }
        }.getOrNull()
    }
}

internal fun parseWebVtt(source: String): List<DetectionTranscriptCue> {
    val normalized = source.replace("\r\n", "\n").replace('\r', '\n')
    val blocks = normalized.split(VTT_BLOCK_SEPARATOR)
    return buildList {
        for (block in blocks) {
            val lines = block.lines().filter { it.isNotBlank() }
            val timingIndex = lines.indexOfFirst { "-->" in it }
            if (timingIndex < 0) continue
            val timing = lines[timingIndex].split("-->", limit = 2)
            val start = parseVttTimestamp(timing[0].trim()) ?: continue
            val end = parseVttTimestamp(timing[1].trim().substringBefore(' ')) ?: continue
            if (end < start) continue
            val text =
                lines
                    .drop(timingIndex + 1)
                    .joinToString(" ")
                    .replace(VTT_TAG, "")
                    .replace("&nbsp;", " ")
                    .replace("&amp;", "&")
                    .replace("&lt;", "<")
                    .replace("&gt;", ">")
                    .replace("&quot;", "\"")
                    .replace("&#39;", "'")
                    .replace(VTT_WHITESPACE, " ")
                    .trim()
            if (text.isNotEmpty()) add(DetectionTranscriptCue(start, end, text))
        }
    }
}

private fun parseVttTimestamp(value: String): Long? {
    val parts = value.split(':')
    if (parts.size !in 2..3) return null
    val secondsParts = parts.last().split('.', limit = 2)
    if (secondsParts.size != 2) return null
    val hours = if (parts.size == 3) parts[0].toLongOrNull() ?: return null else 0L
    val minutes = parts[parts.size - 2].toLongOrNull() ?: return null
    val seconds = secondsParts[0].toLongOrNull() ?: return null
    val milliseconds = secondsParts[1].padEnd(3, '0').take(3).toLongOrNull() ?: return null
    return hours * 3_600_000 + minutes * 60_000 + seconds * 1_000 + milliseconds
}

private val VTT_TAG = Regex("<[^>]+>")
private val VTT_BLOCK_SEPARATOR = Regex("\n{2,}")
private val VTT_WHITESPACE = Regex("\\s+")

private const val TAG = "SponsorDetection"
